# Use official Go image
FROM golang:1.24.4

# Set working directory
WORKDIR /app

# Copy go.mod and go.sum
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy all files
COPY . .

# Build the Go app
RUN go build -o main ./cmd/main.go

# Run the app
CMD ["./main"]
